pipeline {
    agent any

    // 参数化
    parameters {
        string(name: 'REPOSITORY', defaultValue: 'contrastsecuritydemo/spring-petclinic', description: '镜像仓库地址')
        string(name: 'TAG', defaultValue: '1.5.1', description: '镜像 Tag')
        string(name: 'SERVICE_PORT', defaultValue: '8080', description: '服务及 HTTPRoute 后端端口')
        booleanParam(name: 'ENABLE_HTTPROUTE', defaultValue: true, description: '是否渲染并部署 HTTPRoute')
        string(name: 'GATEWAY_NAME', defaultValue: 'springboot-gateway', description: '绑定 Gateway 名称')
    }

    // 全局变量
    environment {
        RELEASE_NAME = 'spring-petclinic-release'
        CHART_NAME   = 'petclinic/generic-deployment'
        NAMESPACE    = 'spring'
        VALUES_FILE  = 'spring-petclinic/prod/values.yaml'
    }

    stages {
        stage('Helm Repo Update') {
            steps {
                sh '''
                    ${HELM_ACK_PROD_BIN} repo update
                '''
            }
        }

        stage('Deploy to ACK Prod') {
            steps {
                script {
                    // 使用 env. 显式读取环境变量，并纠正变量名与参数大小写
                    def helmInstallCmd = "${env.HELM_ACK_PROD_BIN} upgrade --install ${env.RELEASE_NAME} ${env.CHART_NAME} --namespace ${env.NAMESPACE} -f ${env.VALUES_FILE} --set image.repository=${params.REPOSITORY} --set image.tag=${params.TAG} --wait --timeout 5m"
                    echo "CMD: ${helmInstallCmd}"
                    
                    if (sh(returnStatus: true, script: helmInstallCmd) != 0) {
                        sh "${env.HELM_ACK_PROD_BIN} rollback ${env.RELEASE_NAME} --namespace ${env.NAMESPACE}"
                        error "Helm deploy failed, rollback done."
                    }
                }
            }
        }
    }

    post {
        success { 
            echo "Helm Release ${env.RELEASE_NAME} (${params.REPOSITORY}:${params.TAG}) 部署并通过健康检查！" 
        }
        failure { 
            echo "Helm Release ${env.RELEASE_NAME} 部署失败（或 Pod 未就绪），请检查构建日志。" 
        }
    }
}