pipeline {
    agent any

    environment {
        RELEASE_NAME = 'mychart'
        CHART_NAME   = 'petclinic/generic-deployment'
        NAMESPACE    = 'default'
        // 修改这里的相对路径，指向具体的子目录
        VALUES_FILE  = 'zipkin/prod/values.yaml' 
    }

    stages {
        stage('Helm Repo Update') {
            steps {
                sh '''
                    ${HELM_PETCLINIC_PROD_BIN} repo update
                '''
            }
        }

        stage('Deploy to ACK Prod') {
            steps {
                sh '''
                    # 执行部署
                    ${HELM_PETCLINIC_PROD_BIN} upgrade --install ${RELEASE_NAME} ${CHART_NAME} \
                      --namespace ${NAMESPACE} \
                      -f ${VALUES_FILE}
                '''
            }
        }
    }

    post {
        success { echo "Helm Release ${RELEASE_NAME} 部署成功！" }
        failure { echo "Helm Release ${RELEASE_NAME} 部署失败，请检查构建日志。" }
    }
}